### ISSUE TITLE
Does RANDOM_DELAY in cron really work?

### ISSUE THREAD

**Issue by rugk** [matheusd/qubes-borg-rsyncnet#1]
In https://github.com/matheusd/qubes-borg-rsyncnet/blob/da71a758c070c078a19e1aa22e094de7821fe347/template/bak.crontab#L2 you use `RANDOM_DELAY`. I only know this from anacron (i.e. `/etc/anacrontab`), but not for the usual cron.
Does not cron always execute a thing at a certain time?

**Comment by matheusd** [comment]
I double checked man (5) crontab and it does mention RANDOM_DELAY.

I also checked one of the VM's I'm doing backup with this method and for all archives created within a day the minute is the same but it varies among days, consistent with the documented behaviour of RANDOM_DELAY (it is chosen once at daemon startup - I usually start the VM at the start of the day and shut it down at the end).

Sample of backup archives created on this vm:

```
$ borgbak list
[...]
dev-2017-08-11T18:11:09.824988       Fri, 2017-08-11 18:11:14
dev-2017-08-11T19:11:09.776063       Fri, 2017-08-11 19:11:15
dev-2017-08-11T20:11:10.490684       Fri, 2017-08-11 20:11:16
dev-2017-08-14T11:19:13.272647       Mon, 2017-08-14 11:19:19
dev-2017-08-14T12:19:12.422347       Mon, 2017-08-14 12:19:19
dev-2017-08-14T13:19:12.622180       Mon, 2017-08-14 13:19:18
[...]
```

Notice that for Friday all backups were done at the 11 minute mark and for monday they were done at the 19 minute mark.

**Comment by rugk** [comment]
Thanks. :smiley:
